export const COUNTRIES = [
    'Ghana',
    'Nigeria',
    'South Africa',
    'Kenya',
    'Egypt',
    'Morocco',
    'Ivory Coast',
    'Senegal',
    'Togo',
    'Benin',
    'Burkina Faso',
    'Mali',
    'Niger',
    'Liberia',
    'Sierra Leone',
    'Guinea',
    'Cameroon',
    'Ethiopia',
    'Tanzania',
    'Uganda',
    'Rwanda',
    'Zambia',
    'Zimbabwe',
    'Botswana',
    'Namibia',
    'Mozambique',
    'Angola',
    'Algeria',
    'Tunisia',
    'Libya',
    'Sudan',
    'United States',
    'United Kingdom',
    'Canada',
    'Germany',
    'France',
    'Italy',
    'Spain',
    'Portugal',
    'Netherlands',
    'Belgium',
    'Switzerland',
    'Sweden',
    'Norway',
    'Denmark',
    'Finland',
    'Ireland',
    'Austria',
    'Poland',
    'Greece',
    'Turkey',
    'Russia',
    'Ukraine',
    'China',
    'Japan',
    'South Korea',
    'India',
    'Pakistan',
    'Bangladesh',
    'Indonesia',
    'Malaysia',
    'Singapore',
    'Thailand',
    'Vietnam',
    'Philippines',
    'United Arab Emirates',
    'Saudi Arabia',
    'Qatar',
    'Kuwait',
    'Israel',
    'Lebanon',
    'Jordan',
    'Australia',
    'New Zealand',
    'Brazil',
    'Argentina',
    'Mexico',
    'Chile',
    'Colombia',
    'Peru',
    'Other',
];
