export const RELATIONSHIP_OPTIONS = [
    'Father',
    'Mother',
    'Brother',
    'Sister',
    'Son',
    'Daughter',
    'Aunty',
    'Uncle',
    'Grandmother',
    'Grandfather',
    'Cousin',
    'Niece',
    'Nephew',
];
